ORB_Boost_B:
    keypoint_dim: 4
    keypoint_encoder: [32, 64, 128, 256]
    descriptor_dim: 256
    descriptor_encoder: [512, 256]
    Attentional_layers: 4
    last_activation: 'tanh'
    l2_normalization: false
    output_dim: 256


SuperPoint_Boost_F:
    keypoint_dim: 3
    keypoint_encoder: [32, 64, 128, 256]
    descriptor_encoder: [256, 256]
    descriptor_dim: 256
    Attentional_layers: 9
    last_activation:
    l2_normalization: true
    output_dim: 256


SuperPoint_Boost_B:
    keypoint_dim: 3
    keypoint_encoder: [32, 64, 128, 256]
    descriptor_encoder: [256, 256]
    descriptor_dim: 256
    Attentional_layers: 9
    last_activation: 'tanh'
    l2_normalization: false
    output_dim: 256